videos:

  - title: Cinderella Ballet
    date: 1981
    url: 80894739
    duration: 146
    format: vhs

  - title: Blue Lake Fine Arts Camp
    date: July 20, 1986
    url: 80956254
    duration: 108
    format: vhs

  - title: Christmas in Detroit
    date: December 12, 1986
    url: 80983103
    duration: 18
    format: vhs

  - title: Yvonne's Birthday
    date: December 27, 1986
    url: 80988508
    duration: 8
    format: vhs

  - title: Sturgis Variety Show
    date: May 16, 1987
    url: 81367038
    duration: 133
    format: vhs

  - title: Niagra Falls
    date: 1988
    url: 81386809
    duration: 28
    format: vhs

  - title: Road Trip
    date: July 15, 1989
    url: 81122230
    duration: 16
    format: vhs

  - title: The Pena's
    date: July 16, 1989
    url: 81366112
    duration: 16
    format: vhs

  - title: Atlantic City
    date: July 17, 1989
    url: 81492492
    duration: 21
    format: vhs

  - title: New York City
    date: July 18, 1989
    url: 82554519
    duration: 24
    format: vhs

  - title: Princeton
    date: July 19, 1989
    url: 81105123
    duration: 7
    format: vhs

  - title: Washington D.C.
    date: July 20, 1989
    url: 82533823
    duration: 28
    format: vhs

  - title: Grandpa Mickey's
    date: August 5, 1989
    url: 81365780
    duration: 6
    format: vhs

  - title: Lorna's Kirsch Party
    date: January 26, 1990
    url: 81996975
    duration: 44
    format: vhs

  - title: SHS Graduation 1990
    date: 1990
    url: 82534402
    duration: 58
    format: vhs

  - title: Royal Caribbean Cruise
    date: December, 1993
    url: 82093308
    duration: 19
    format: vhs

  - title: Royal Caribbean Cruise
    date: December, 1993
    url: 82384358
    duration: 117
    format: 8mm

  - title: Royal Caribbean Cruise
    date: December, 1993
    url: 82535551
    duration: 23
    format: 8mm

  - title: The Cottage
    date: July 4, 1994
    url: 81072733
    duration: 16
    format: 8mm

  - title: Das Essen Haus
    date: July 6, 1995
    url: 81364901
    duration: 5
    format: 8mm

  - title: SHS Girls Tennis Video
    date: 1996
    url: 81596820
    duration: 10
    format: vhs

  - title: Brokenshire Reunion
    date: 1997
    url: 81994312
    duration: 69
    format: vhs

  - title: Anne & Vince's Wedding Day
    date: October 6, 2012
    url: 72575362
    duration: 8
    format: HD

  - title: In Memory of Sufragista DeGuzman
    date: 2014
    url: 86629336
    duration: 11
    format: slideshow

  - title: Karen's 40th Birthday Video Card
    date: July 2, 2014
    url: 99841383
    duration: 2
    format: HD

  - title: For Elliott Revitte
    date: July 29, 2014
    url: 102020636
    duration: 2
    format: HD

  - title: Dad and Mom's Retirement Party
    date: September 28, 2014
    url: 108800438
    duration: 19
    format: HD

  - title: Elliott's Easter JibJab
    date: April 5, 2015
    url: 122335891
    duration: 2
    format: HD

  - title: Phoebe's 1st Birthday JibJab
    date: May 14, 2015
    url: 128270550
    duration: 2
    format: HD

  - title: Uncle Ronnie's 60th Birthday Slideshow
    date: April 24, 2015
    url: 128299302
    duration: 10
    format: HD
