videos:

  - title: Cinderella Ballet
    date: 1981
    url: 80894739
    duration: 146

  - title: Blue Lake Fine Arts Camp
    date: July 20, 1986
    url: 80956254
    duration: 108

  - title: Christmas in Detroit
    date: December 12, 1986
    url: 80983103
    duration: 18

  - title: Yvonne's Birthday
    date: December 27, 1986
    url: 80988508
    duration: 8

  - title: Sturgis Variety Show
    date: May 16, 1987
    url: 81367038
    duration: 133

  - title: Niagra Falls
    date: 1988
    url: 81386809
    duration: 28

  - title: Road Trip
    date: July 15, 1989
    url: 81122230
    duration: 16

  - title: The Pena's
    date: July 16, 1989
    url: 81366112
    duration: 16

  - title: Atlantic City
    date: July 17, 1989
    url: 81492492
    duration: 21

  - title: Princeton
    date: July 19, 1989
    url: 81105123
    duration: 7

  - title: Washington D.C.
    date: July 20, 1989
    url: 82533823
    duration: 28

  - title: Grandpa Mickey's
    date: August 5, 1989
    url: 81365780
    duration: 6

  - title: Lorna's Kirsch Party
    date: January 26, 1990
    url: 81996975
    duration: 44

  - title: SHS Graduation 1990
    date: 1990
    url: 82534402
    duration: 58

  - title: Royal Caribbean Cruise
    date: December, 1993 VHS tape
    url: 82093308
    duration: 19

  - title: Royal Caribbean Cruise
    date: December, 1993, 8mm tape 1
    url: 82384358
    duration: 117

  - title: Royal Caribbean Cruise
    date: December, 1993, 8mm tape 2
    url: 82535551
    duration: 23

  - title: The Cottage
    date: July 4, 1994
    url: 81072733
    duration: 16

  - title: Das Essen Haus
    date: July 6, 1995
    url: 81364901
    duration: 5

  - title: SHS Girls Tennis Video
    date: 1996
    url: 81596820
    duration: 10

  - title: Brokenshire Reunion
    date: 1997
    url: 81994312
    duration: 69
