videos:

  - title: Cinderella Ballet
    date: 1981
    url: 80894739

  - title: Blue Lake Fine Arts Camp
    date: July 20, 1986
    url: 80956254

  - title: Christmas in Detroit
    date: December 12, 1986
    url: 80983103

  - title: Yvonne's Birthday
    date: December 27, 1986
    url: 80988508

  - title: Sturgis Variety Show
    date: May 16, 1987
    url: 81367038

  - title: Niagra Falls
    date: 1988
    url: 81386809

  - title: Road Trip
    date: July 15, 1989
    url: 81122230

  - title: The Pena's
    date: July 16, 1989
    url: 81366112

  - title: Atlantic City
    date: July 17, 1989
    url: 81492492

  - title: Princeton
    date: July 19, 1989
    url: 81105123

  - title: Washington D.C.
    date: July 20, 1989
    url: 82533823

  - title: Grandpa Mickey's
    date: August 5, 1989
    url: 81365780

  - title: Lorna's Kirsch Party
    date: January 26, 1990
    url: 81996975

  - title: SHS Graduation 1990
    date: 1990
    url: 82534402

  - title: Royal Caribbean Cruise
    date: December, 1993 VHS tape
    url: 82093308

  - title: Royal Caribbean Cruise
    date: December, 1993, 8mm tape 1
    url: 82384358

  - title: The Cottage
    date: July 4, 1994
    url: 81072733

  - title: Das Essen Haus
    date: July 6, 1995
    url: 81364901

  - title: SHS Girls Tennis Video
    date: 1996
    url: 81596820

  - title: Brokenshire Reunion
    date: 1997
    url: 81994312
